version: '3'
services:
  django:
    build: .
    container_name: ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=lifeless
      - POSTGRES_PASSWORD=56a78k12b34c
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
volumes:
  pgdbdata: null